global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: DEBUG

api:
  dashboard: true
  insecure: false  # Secure dashboard access
  debug: false

entryPoints:
  web:
    address: :80
    # redirect all http traffic to https
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false
    endpoint: 'unix:///var/run/docker.sock'
    watch: true
    swarmMode: false

# TLS configuration - enable verification in production
serversTransport:
  insecureSkipVerify: false  # Changed to secure default
  maxIdleConnsPerHost: 10
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 0s
tls:
  certificates:
    - certFile: /certs/cert.crt
      keyFile: /certs/cert.key