{
 "title": "🤖 Robot Maid",
 "tags": [ "homeassistant" ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current Vacuum State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_state{entity=\"sensor.roborock_state_numeric\"}",
     "legendFormat": "{{entity_id}}"
    }
   ]
  },
  {
   "title": "Cleaning Area Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_mu0xb2",
     "legendFormat": "{{entity_id}}"
    }
   ]
  },
  {
   "title": "Main Brush Life Remaining",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_duration_h{entity=~\".*main_brush.*\"}",
     "legendFormat": "{{entity_id}}"
    }
   ]
  },
  {
   "title": "Filter Life",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_duration_h{entity=~\".*filter.*\"}",
     "legendFormat": "{{entity_id}}"
    }
   ]
  },
  {
   "title": "Dock Strainer Life",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_duration_h{entity=~\".*dock_strainer.*|.*side_brush.*|.*sensor_time.*\"}",
     "legendFormat": "{{entity_id}}"
    }
   ]
  },
  {
   "title": "Cleaning Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_duration_min",
     "legendFormat": "Cleaning time (min)"
    }
   ]
  }
 ]
}