variable "project_name" {
  description = "Project name prefix for resource naming"
  type        = string
  default     = "homelab"
}

variable "teleport_version" {
  description = "Teleport version to deploy (must match the cluster version)"
  type        = string
  default     = "15.5.4"
}

variable "teleport_proxy_address" {
  description = "Public address of the Teleport proxy (e.g. tp.rainforest.tools:443)"
  type        = string
}

variable "auth_token" {
  description = "Join token generated by the Teleport auth server for this node"
  type        = string
  sensitive   = true
}

variable "node_name" {
  description = "Unique name for this node in the Teleport cluster"
  type        = string
  default     = "raspberry-pi-5"
}

variable "enable_ssh" {
  description = "Register this node for SSH access via Teleport (in addition to app access)"
  type        = bool
  default     = true
}

variable "apps" {
  description = "Map of Teleport Applications to register (Pi web services)"
  type = map(object({
    uri         = string
    description = string
  }))
  default = {}
}

variable "hostname" {
  description = "SSH hostname / IP of the Raspberry Pi"
  type        = string
}

variable "ssh_user" {
  description = "SSH username for provisioning the Teleport config on the Pi"
  type        = string
  default     = "rainforest"
}

variable "ssh_port" {
  description = "SSH port on the Raspberry Pi"
  type        = number
  default     = 22
}

variable "ssh_private_key" {
  description = "Path to SSH private key file (leave empty to use ssh-agent)"
  type        = string
  default     = ""
  sensitive   = true
}

variable "timezone" {
  description = "Timezone for the container"
  type        = string
  default     = "Asia/Taipei"
}

variable "log_opts" {
  description = "Docker log driver options"
  type        = map(string)
  default = {
    "max-size" = "50m"
    "max-file" = "3"
  }
}
