# Ansible Inventory for Homelab
all:
  children:
    raspberry_pi:
      hosts:
        raspberrypi-5:
          ansible_host: raspberrypi-5
          ansible_user: rainforest
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          
          # Pi-specific variables
          pi_model: "5"
          memory_gb: 8
          architecture: "arm64"
          
    mac_mini:
      hosts:
        mac-mini-m4:
          ansible_host: 100.86.67.66  # Tailscale IP
          ansible_user: rainforest
          
          # Mac-specific variables
          docker_host: "dockerproxy.orb.local:2375"
          
    # Future expansion
    github_runners:
      hosts:
        # pc-runner:
        #   ansible_host: TBD
        #   ansible_user: runner

  vars:
    # Global homelab variables
    timezone: "Asia/Taipei"
    dns_servers:
      - "1.1.1.1"
      - "1.0.0.1"
    
    # Monitoring configuration
    monitoring:
      enable_prometheus: true
      enable_grafana: true
      enable_loki: true